import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Providers from './providers';
import Sidebar from '@/components/Sidebar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Eaternal',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div>
            <div className="gradient-bg-sidebar w-full fixed">
              <Sidebar />
            </div>
            <div className="h-screen overflow-y-auto pt-[104px]">{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
